export const ACTIONS = {
  FORMIGO_INPUT_SET_SERVER_ERRORS: 'FORMIGO_INPUT_SET_SERVER_ERRORS',
  SET_FORMIGO_ATTR_ERRORS: 'SET_FORMIGO_ATTR_ERRORS',
  SET_FORMIGO_ATTR_VALUE: 'SET_FORMIGO_ATTR_VALUE',
};
